INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (1, 'ana@mail.com', '2025-09-10 14:00', 'Temperatura alta', '32°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (2, 'ana@mail.com', '2025-09-10 20:00', 'Luz encendida', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (3, 'bruno@mail.com', '2025-09-10 15:30', 'Movimiento detectado', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (4, 'carla@mail.com', '2025-09-10 16:00', 'Ventilador encendido', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (5, 'david@mail.com', '2025-09-10 19:00', 'Gas detectado', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (6, 'emma@mail.com', '2025-09-10 07:00', 'Luz apagada', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (7, 'ana@mail.com', '2025-09-11 08:00', 'Temperatura normal', '24°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (8, 'bruno@mail.com', '2025-09-11 09:15', 'Puerta abierta', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (9, 'carla@mail.com', '2025-09-11 10:00', 'Ventilador apagado', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (10, 'david@mail.com', '2025-09-11 11:30', 'Gas no detectado', 'No');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (11, 'emma@mail.com', '2025-09-11 12:00', 'Luz encendida', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (12, 'ana@mail.com', '2025-09-11 13:00', 'Temperatura baja', '18°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (13, 'bruno@mail.com', '2025-09-11 14:45', 'Movimiento no detectado', 'No');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (14, 'carla@mail.com', '2025-09-11 15:30', 'Ventilador encendido', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (15, 'david@mail.com', '2025-09-11 16:00', 'Gas detectado', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (16, 'emma@mail.com', '2025-09-11 17:00', 'Luz apagada', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (17, 'ana@mail.com', '2025-09-12 07:30', 'Temperatura alta', '30°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (18, 'bruno@mail.com', '2025-09-12 08:15', 'Puerta cerrada', 'No');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (19, 'carla@mail.com', '2025-09-12 09:00', 'Ventilador apagado', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (20, 'david@mail.com', '2025-09-12 10:30', 'Gas no detectado', 'No');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (21, 'emma@mail.com', '2025-09-12 11:00', 'Luz encendida', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (22, 'ana@mail.com', '2025-09-12 12:15', 'Temperatura normal', '23°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (23, 'bruno@mail.com', '2025-09-12 13:00', 'Movimiento detectado', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (24, 'carla@mail.com', '2025-09-12 14:30', 'Ventilador encendido', 'ON');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (25, 'david@mail.com', '2025-09-12 15:00', 'Gas detectado', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (26, 'emma@mail.com', '2025-09-12 16:45', 'Luz apagada', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (27, 'ana@mail.com', '2025-09-13 08:00', 'Temperatura baja', '17°C');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (28, 'bruno@mail.com', '2025-09-13 09:30', 'Puerta abierta', 'Sí');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (29, 'carla@mail.com', '2025-09-13 10:00', 'Ventilador apagado', 'OFF');
INSERT INTO EventoDispositivo (id_dispositivo, email, fecha_hora, detalle, valor) VALUES (30, 'david@mail.com', '2025-09-13 11:30', 'Gas no detectado', 'No');
